import { AIProviderInterface, AIResponse, ModerationResponse, PrivacyRating, DeploymentMode } from '../types';

export class BaseMockProvider implements AIProviderInterface {
  id: string;
  name: string;
  version: string;
  
  protected _latency: number;
  protected _costPerToken: number;
  protected _privacyLevel: PrivacyRating;
  protected _deploymentModes: DeploymentMode[];

  constructor(id: string, name: string, version: string, latency: number, costPerToken: number, privacy: PrivacyRating, modes: DeploymentMode[]) {
    this.id = id;
    this.name = name;
    this.version = version;
    this._latency = latency;
    this._costPerToken = costPerToken;
    this._privacyLevel = privacy;
    this._deploymentModes = modes;
  }

  protected async simulateDelay() {
    return new Promise(resolve => setTimeout(resolve, this._latency));
  }

  protected createMockResponse(text: string, tokens: number = 150): AIResponse {
    return {
      text,
      confidence: 0.9 + (Math.random() * 0.08),
      latencyMs: this._latency + Math.random() * 50,
      modelUsed: this.id,
      provider: this.name,
      dataResidency: this._deploymentModes.includes('Offline') ? 'Local' : 'Provider Region',
      tokenUsage: tokens,
      reasoning: 'Derived from simulated mock processing based on input context.',
      supportingSignals: ['Historical Data', 'Context Rules'],
      dataSources: ['Mock DB']
    };
  }

  async generate(prompt: string, options?: any): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Generated by ${this.name}] Processed prompt: ${prompt.substring(0, 50)}...`);
  }

  async chat(messages: any[], options?: any): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Chat by ${this.name}] Responding to ${messages.length} messages.`);
  }

  async reason(prompt: string, context: any): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Reasoning by ${this.name}] Analyzed context and prompt.`);
  }

  async summarize(text: string): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Summary by ${this.name}] Summarized ${text.length} chars.`);
  }

  async extract(text: string, schema: any): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Extraction by ${this.name}] Extracted entities matching schema.`);
  }

  async score(text: string, criteria: any): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Score by ${this.name}] 85/100`);
  }

  async classify(text: string, categories: string[]): Promise<AIResponse> {
    await this.simulateDelay();
    return this.createMockResponse(`[Classification by ${this.name}] Categorized as ${categories[0] || 'Unknown'}.`);
  }

  async embed(text: string): Promise<number[]> {
    await this.simulateDelay();
    return Array(1536).fill(0).map(() => Math.random());
  }

  async moderate(text: string): Promise<ModerationResponse> {
    await this.simulateDelay();
    return {
      flagged: false,
      categories: {},
      riskLevel: 'Low'
    };
  }

  async stream(prompt: string, onToken: (token: string) => void): Promise<void> {
    const tokens = `[Streamed by ${this.name}] Response to: ${prompt.substring(0,20)}...`.split(' ');
    for (const t of tokens) {
      await new Promise(resolve => setTimeout(resolve, this._latency / tokens.length));
      onToken(t + ' ');
    }
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }

  costEstimate(tokens: number): number {
    return tokens * this._costPerToken;
  }

  latency(): number { return this._latency; }
  capabilities(): string[] { return ['generate', 'chat', 'reason', 'summarize', 'extract', 'classify']; }
  supportedLanguages(): string[] { return ['en', 'hi', 'fr', 'ja', 'es']; }
  supportedModels(): string[] { return [this.id]; }
  privacyLevel(): PrivacyRating { return this._privacyLevel; }
  deploymentModes(): DeploymentMode[] { return this._deploymentModes; }
}
